# Generated by Django 2.0.5 on 2018-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_url',
            field=models.URLField(default='/'),
            preserve_default=False,
        ),
    ]
