# Generated by Django 2.0.5 on 2018-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180528_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content_text',
            field=models.TextField(max_length=1000),
        ),
    ]
