# Generated by Django 2.0.5 on 2018-05-29 19:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180529_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
