# Generated by Django 2.0.5 on 2018-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180529_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content_text',
            field=models.TextField(max_length=500),
        ),
    ]
