# Generated by Django 2.0.5 on 2018-05-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_pagemenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemenu',
            old_name='menuImage',
            new_name='menu_image',
        ),
        migrations.RenameField(
            model_name='pagemenu',
            old_name='menuLinks',
            new_name='menu_links',
        ),
    ]
