# Generated by Django 2.0.5 on 2018-05-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180530_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagemenu',
            name='menu_links',
        ),
        migrations.AddField(
            model_name='pagemenu',
            name='menu',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menulink',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PageMenu'),
        ),
    ]
