# Generated by Django 2.0.5 on 2018-05-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180530_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='links',
        ),
        migrations.AddField(
            model_name='menulink',
            name='link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.Page', to_field='page_url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.URLField(unique=True),
        ),
    ]
