# Generated by Django 2.0.5 on 2018-05-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180530_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content_text',
            field=models.TextField(),
        ),
    ]
